name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: # do not build for game-irrelvant changes
      - ".**"
      - "LICENSE"
      - "**.md"

env:
  GODOT_VERSION: 4.1-stable
  EXPORT_DIR: DPA-Win
  ITCH_USERNAME: iznaut
  ITCH_GAME_ID: dorkus-playtest-assistant

jobs:
  build:
    name: Export Godot Project
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v3

      - name: export with Godot Engine
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_export_templates.tpz
          relative_project_path: ./
          relative_export_path: ./$EXPORT_DIR
          cache: true

  include_obs:
    name: Add DorkusOBS to export
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: dobs
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: nogoblin/dorkus-obs

      - name: Download DorkusOBS
        run: wget https://github.com/nogoblin/dorkus-obs/releases/download/${{ steps.dobs.outputs.release }}/dorkus-obs.zip
        
      - name: Unzip DorkusOBS to build folder
        run: unzip dorkus-obs.zip -d ./$EXPORT_DIR

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: include_obs
    steps:
      - name: Deploy to itch.io (Windows)
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.ITCH_API_KEY }}
          gameData: ./${{ env.EXPORT_DIR }}
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: win
          buildNumber: 0.1.1
