name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore: # do not build for game-irrelvant changes
      - ".**"
      - "LICENSE"
      - "**.md"

env:
  GODOT_VERSION: 4.1-stable
  ITCH_USERNAME: iznaut
  ITCH_GAME_ID: dorkus-playtest-assistant

jobs:
  build:
    name: Export Godot Project
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v3

      - name: export with Godot Engine
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_export_templates.tpz
          relative_project_path: ./
          relative_export_path: ./build
          cache: true

      - id: dobs
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: nogoblin/dorkus-obs

      - name: Cache DorkusOBS
        id: cache-dobs
        uses: actions/cache@v3
        with:
          path: dorkus-obs.zip
          key: dobs-${{ steps.dobs.outputs.release }}

      - name: Download DorkusOBS
        if: steps.cache-dobs.outputs.cache-hit != 'true'
        run: wget https://github.com/nogoblin/dorkus-obs/releases/download/${{ steps.dobs.outputs.release }}/dorkus-obs.zip

      - name: Unzip DorkusOBS to build folder
        run: unzip dorkus-obs.zip -d ./build/win  

      - name: Deploy (Windows)
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.ITCH_API_KEY }}
          gameData: ./build/win
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: win
