name: Build and Publish

on:
  push:
    branches:
      - main
    paths-ignore: # do not build for game-irrelvant changes
      - ".**"
      - "LICENSE"
      - "ACKNOWLEDGEMENTS"
      - "**.md"

jobs:
  build_game:
    name: Build and Publish Game
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v3

      - name: export with Godot Engine
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_export_templates.tpz
          relative_project_path: ./
          relative_export_path: ./build
          archive_output: true
          use_godot_3: false

      - name: deploy windows build
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCH_API_KEY}}
          gameData: ./build/Windows Desktop.zip
          itchUsername: iznaut
          itchGameId: dorkus-playtest-assistant
          buildChannel: win
          buildNumber: 0.1
