name: Build

on:
  push:
    branches:
      - main
    paths-ignore: # do not build for game-irrelvant changes
      - ".**"
      - "LICENSE"
      - "ACKNOWLEDGEMENTS"
      - "**.md"

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v3

      - name: export with Godot Engine
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0.2/Godot_v4.0.2-stable_export_templates.tpz
          relative_project_path: ./
          relative_export_path: ./build
          archive_output: true
          use_godot_3: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload:
    name: Publish App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: download latest Windows build
        id: download-win
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: DorkusAssist.exe
          token: "${{ secrets.GITHUB_TOKEN }}"